/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index: Record<string, any> = {
  index: {
    name: 'index',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    categories: undefined,
    meta: undefined,
  },
  style: {
    name: 'style',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    categories: undefined,
    meta: undefined,
  },
  accordion: {
    name: 'accordion',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/accordion.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'alert-dialog': {
    name: 'alert-dialog',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/alert-dialog.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  alert: {
    name: 'alert',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/alert.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'aspect-ratio': {
    name: 'aspect-ratio',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/aspect-ratio.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  avatar: {
    name: 'avatar',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/avatar.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  badge: {
    name: 'badge',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/badge.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  breadcrumb: {
    name: 'breadcrumb',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/breadcrumb.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'button-group': {
    name: 'button-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['separator'],
    files: [
      {
        path: 'registry/new-york-v4/ui/button-group.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  button: {
    name: 'button',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/button.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  card: {
    name: 'card',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/card.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  checkbox: {
    name: 'checkbox',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/checkbox.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  collapsible: {
    name: 'collapsible',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/collapsible.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  command: {
    name: 'command',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['dialog'],
    files: [
      {
        path: 'registry/new-york-v4/ui/command.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'context-menu': {
    name: 'context-menu',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/context-menu.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  dialog: {
    name: 'dialog',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/dialog.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'dropdown-menu': {
    name: 'dropdown-menu',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/dropdown-menu.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  empty: {
    name: 'empty',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/empty.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  field: {
    name: 'field',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['label', 'separator'],
    files: [
      {
        path: 'registry/new-york-v4/ui/field.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'hover-card': {
    name: 'hover-card',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/hover-card.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'input-group': {
    name: 'input-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['button', 'input', 'textarea'],
    files: [
      {
        path: 'registry/new-york-v4/ui/input-group.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'input-otp': {
    name: 'input-otp',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/input-otp.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  input: {
    name: 'input',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/input.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  item: {
    name: 'item',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['separator'],
    files: [
      {
        path: 'registry/new-york-v4/ui/item.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  kbd: {
    name: 'kbd',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/kbd.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  label: {
    name: 'label',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/label.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'native-select': {
    name: 'native-select',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/native-select.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  pagination: {
    name: 'pagination',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/pagination.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  popover: {
    name: 'popover',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/popover.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  progress: {
    name: 'progress',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/progress.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'radio-group': {
    name: 'radio-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/radio-group.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'scroll-area': {
    name: 'scroll-area',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/scroll-area.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  select: {
    name: 'select',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/select.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  separator: {
    name: 'separator',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/separator.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  sheet: {
    name: 'sheet',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/sheet.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  sidebar: {
    name: 'sidebar',
    description: '',
    type: 'registry:ui',
    registryDependencies: [
      'button',
      'input',
      'separator',
      'sheet',
      'skeleton',
      'tooltip',
    ],
    files: [
      {
        path: 'registry/new-york-v4/ui/sidebar.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  skeleton: {
    name: 'skeleton',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/skeleton.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  slider: {
    name: 'slider',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/slider.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  sonner: {
    name: 'sonner',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['toast'],
    files: [
      {
        path: 'registry/new-york-v4/ui/sonner.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  spinner: {
    name: 'spinner',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/spinner.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  switch: {
    name: 'switch',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/switch.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  table: {
    name: 'table',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/table.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  tabs: {
    name: 'tabs',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/tabs.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  textarea: {
    name: 'textarea',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/textarea.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  'toggle-group': {
    name: 'toggle-group',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['toggle'],
    files: [
      {
        path: 'registry/new-york-v4/ui/toggle-group.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  toggle: {
    name: 'toggle',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/toggle.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  tooltip: {
    name: 'tooltip',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/ui/tooltip.gts',
        type: 'registry:ui',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  utils: {
    name: 'utils',
    description: '',
    type: 'registry:lib',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/lib/utils.ts',
        type: 'registry:lib',
        target: '',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
  toast: {
    name: 'toast',
    description: '',
    type: 'registry:composable',
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/new-york-v4/services/toast.ts',
        type: 'registry:composable',
        target: 'app/services/toast.ts',
      },
    ],
    categories: undefined,
    meta: undefined,
  },
};
